### ISSUE TITLE
Search Panel too wide .. cannot see Edit Button

### ISSUE THREAD

**Issue by adxsoft** [Leleat/AGodotCodeSnippetPlugin#2]
I am running Godot 3.2.2 stable on Mac OSX Sierra. I installed this plugin and enabled it in the Plugins list in the Project settings.

Ctrl Tab displays the search box however much wider than the screen so the edit button is hidden (ie. to the right of the screen area).

Obviously just a sizing issue for the search panel but unfortunately makes the plugin unusable for now on my Mac.

I'm sure once this is fixed this will be a great plugin for productivity

![Screen Shot 2020-08-09 at 7 40 30 am](https://user-images.githubusercontent.com/24862237/89720290-ad015180-da13-11ea-85c7-4e03dcb41d40.png)

**Comment by Leleat** [comment]
I just tested it on 3.2.2 and it works for me (just like in the preview gifs).

I guess it's because of your HiDPI screen. I tried to use a very naive way to scale my addon for them but it seems like it didn't work (hard to test because I don't have one myself). I removed it now. Can you download the addons folder manually and add it to your project? I think the popup window should be fairly small now. I exported the popup window size as a variable. Please open /addons/CodeSnippetPopup/CodeSnippetPopup.tscn in your Godot project and change the window size in the inspector as you see fit. If this works, I will add a settings page where people can edit the size so they don't have to directly edit the addon files.

One problem you may have, is that the position of the "choices" (see first preview gif) is not directly under the cursor. As far as I know Godot doesn't provide a way to get the text cursor position (neither local nor global). So I had to calculate that by myself. But HiDPI screens will likely have problems. Please check and report back to me.

**Comment by adxsoft** [comment]
Wow .. thanks for the quick response .. much appreciated.

Downloaded the addon and added to project addon folder and now it works fine here is my result.

I do have a 32 inch monitor the Philips curved Ultra.

Heres what it looks like now .. without the curve :=)


Thanks
Allan @ adxsoft

**Comment by Leleat** [comment]
I think you forgot to add the screeshot to your last message :)
Did you test the multiple choices function of the addon? If so, did the popup with the choices appear at the correct position (under the text cursor)? 

I added a settings page now and submitted it to the AssetLib. So it should be up within a week or so.

**Comment by adxsoft** [comment]
Hi there

All working well there were however a few glitches documented below.

I downloaded v1.03 from the Asset Library after removing all versions of 1.02

Two minor problems with v1.03 download were

 1. It wouldn’t Update  - I found it still had v1.02 in the plugin.cfg file.
 2. CodeSnippetPopup.cfg file did not include these two snippets that were in the previous version

      [---- I'm an just example. ----]
body="\"This is the main body, which gets inserted. The first [@1][@2] marks the cursor position after the snippet has been inserted. It will however not be included. 
You can have multiple jump positions. For ex. After THIS [@3] is the third jump position. You can escape the jumping by quickly double tapping the keyboard shortcut."
type_hint="
If 'Add Type Hint'[@4] is enabled in the EditorSettings and this key is defined, it will be inserted right after the body.\""
no_type_hint="
If 'Add Type Hint'[@4] is not enabled in the EditorSettings and this key is defined, it will be inserted right after the body.\""
additional_info="Click the 'Edit' button to see how I work. Feel free to delete me!"

[---- Mirrored/dropdown var example. ----]
body = "var [@1:array,arr,test] : Array
for [@2:i] in [@1].size(): # mirrored from the line above
	print([@2])
return [@1] # then jump to here [@7] and next
# no [@4:nom,nim,num,nam] test [@4][@8]"
additional_info="Just another example you can delete."


I then manually copied the v1.03 CodeSnippetPopup folder to the addons folder in a sample Godot Project and enabled it

 - Ctrl Tab opened the pop and I was able to confirm the following working
   - snippets inserted correctly
   - tab points @n were jumped to correctly
   - Settings seem ok
  - all displays were shown correctly on my HDPI screen

So in conclusion

- I really like this tool and i’m already finding it very productive!

- Suggest you add a version no somewhere in the display to be clear which version one is using (Matbe an about popup?)
  This is because the plugin gets manually copied to each project and old versions can therefore hand around
  (It would be nice if Godot could point to one plugin folder rather than copying the plugins everywhere

- It took me a while to realise that once a snippet is inserted I use Ctrl tab to do the jumps. The help text could be updated as follows to make this clearer.

INI-style structure.

The [section] is the snippet name and it is the name which will appear in the list.

"body" (without quotations marks) is the only key which has to be defined. Optional keys are:
"type_hint" will be inserted after "body" only if type hints are enabled in Godot's editor settings. 
"no_type_hint" will be inserted after "body" only if type hints are disabled in Godot's editor settings. 
"additional_info" will appear in the snippet list but greyed out. It won't be inserted anywhere  when activating a snippet. 

Use [@X] in your snippets, where X is an integer, to mark the position(s) the cursor jumps to when pressing the shortcut after snippet insertion. The order of the numbers will be respected. If you use a number multiple times, the code you used for the first X will be mirrored to the other markers. 

You can add a placeholder/dropdown options by separating the options by commas. For example: [@1:OptionA,OptionB] will be the first position the cursor will jump to after the snippet has been inserted. A popup window will open with "OptionA" and "OptionB" as choices under the text cursor position.

Press Esc  will abort the tabstop jumping for the current snippet. If the dropdown choice popup is visible you will need to press Esc twice (one to escape the choice popup and a second time to escape the jumping).

Using the cursor jumps.

Once the snippet has been inserted into text in the editor screen you can move the cursor to the [@X] point in the text using the Control-Tab shortcut key (or the keyboard shortcut you have chosen in Settings)  
  
Finally  here are the screenshots on my Mac which all worked on the wide screen with no issues



Cheers
Allan @ adxsoft

**Comment by adxsoft** [comment]
[CodeSnippet Screenshots.zip](https://github.com/Leleat/AGodotCodeSnippetPlugin/files/5067563/CodeSnippet.Screenshots.zip)

Here are the screenshots. Not sure why I have had to drag them into this comment as I did attach them to the email reply. Anyway hope you can see them now.
Cheers
Allan

**Comment by adxsoft** [comment]
PS.

Another thought that occurs to me is the CodeSnippetPopup.cfg file contains the snippets. In order to always have the latest snippets in each project you need a master copy of CodeSnippetPopup.cfg that you manually copy into each new project.
It would be a good idea to have a setting for a location of the snippets file. In this way you can have only ONE external snippets file rather than lots of copies strewn about all the projects. Also you can keep the external snippets file under proper version control.

Let me know what you think.

Cheers
Allan @ adxsoft

**Comment by Leleat** [comment]
>  1. It wouldn’t Update  - I found it still had v1.02 in the plugin.cfg file.

Sorry, just forgot to bump up the number. I am still new to software development ;)

>  2. CodeSnippetPopup.cfg file did not include these two snippets that were in the previous version

I moved the 2 examples to the help page. So that if someone deletes them, they always have a way back to relook at the examples.

>   - all displays were shown correctly on my HDPI screen

A while back I had someone report that on their MacBook the Options-dropdown was slightly offset from the text cursor position (horizontally and vertically). That is why I tried to use a simple workaround for that (which I removed now since it didn't seem to work for you). **Do you use the scaling options (120%) on your Mac?**

> Suggest you add a version no somewhere in the display to be clear which version one is using

Sounds good. I'll add it.

> It took me a while to realise that once a snippet is inserted I use Ctrl tab to do the jumps. The help text could be updated as follows to make this clearer.

Will update the help page.

**Comment by adxsoft** [comment]
Hi..No I don't use any scaling options. I've tried the Options-dropdown on my large HDPI screen (which is an external screen from my 13inch Macbook Air. I disconnected the external screen and on the 13inch screen the positioning of the dropdown looks fine. I did notice the dropdown stays in a fixed position of you scroll the text in the editor screen which might be why they thought the positioning was incorrect. 

I also checked this on Windows 10 and the dropdown positioning is fine

**Comment by Leleat** [comment]
> I disconnected the external screen and on the 13inch screen the positioning of the dropdown looks fine

Do you use scaling on the 13" screen?

**Comment by adxsoft** [comment]
No .. I’ve never adjusted the scaling. I’ve always had the Display setting (System Preferences -> Displays) set to ‘Default for Display’
I set scaling on and tried 1080p and 1600x900 and on both resolutions the dropdown positioned correctly

**Comment by Leleat** [comment]
I've created a branch, which should adress this and #4. Once I implemented #5, I'll merge it into master and resubmit to the AssetLib.

**Comment by adxsoft** [comment]
Tested the branch and the global script file works perfectly..thanks
Cheers
Allan @ adxsoft

**Comment by adxsoft** [comment]
I tried another test and I can’t explain what is happening

I changed the Snippets file location in settings to my external snippets file eg. /User/allandavies/Developer/Godot/Snippets/MySnippets.txt

As expected all my snippets appeared in the list and inserted perfectly.

I then changed the setting to a junk name /User/allandavies/Developer/Godot/Snippets/MySnippets12345.txt and tapped the Edit button and it
still showed my snippets (even though they weren’t in CodeSnippets.cfg in the user:// folder) ?? 

I would have thought it should have crashed or given me a warning that the snippet file I’m pointing to doesn’t exist

This is the only thing I have discovered since the initial test of this branch.

Cheers
Allan @ adsxoft

**Comment by Leleat** [comment]
> As expected all my snippets appeared in the list and inserted perfectly.
> 
> I then changed the setting to a junk name /User/allandavies/Developer/Godot/Snippets/MySnippets12345.txt and tapped the Edit button and it
> still showed my snippets (even though they weren’t in CodeSnippets.cfg in the user:// folder) ??

That is intentional. If the file path changes to an existing file, the existing file will be used. If the file doesn't exist at the new file path, the old snippets will be copied over. 
I thought that was better since it is easier to delete all snippets at the new file than having to import all old snippets into the new file.

Do you think that is unintuitive and should be changed?

**Comment by adxsoft** [comment]
Aha I understand  .. rhars a good approach.


On Aug 14, 2020 at 8:43 PM, Leleat <notifications@github.com> wrote:

As expected all my snippets appeared in the list and inserted perfectly.

I then changed the setting to a junk name
/User/allandavies/Developer/Godot/Snippets/MySnippets12345.txt and tapped
the Edit button and it
still showed my snippets (even though they weren’t in CodeSnippets.cfg in
the user:// folder) ??

That is intentional. If the file path changes to an existing file, the
existing file will be used. If the file doesn't exist at the new file path,
the old snippets will be copied over.
I thought that was better since it is easier to delete all snippets at the
new file than having to import all old snippets into the new file.

Do you think that is unintuitive and should be changed?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Leleat/AGodotCodeSnippetPlugin/issues/2#issuecomment-674013940>,
or unsubscribe
